language: node_js

sudo: required

services:
  - docker

install:
  - docker pull agileiot/agile-nodered-armv7l
  - docker pull agileiot/agile-nodered-armv7l:$TRAVIS_BRANCH || true
script:
  - docker build -t agileiot/agile-nodered-armv7l:$TRAVIS_BRANCH .
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push agileiot/agile-nodered-armv7l:$TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag agileiot/agile-nodered-armv7l:$TRAVIS_BRANCH agileiot/agile-nodered-armv7l;
      docker push agileiot/agile-nodered-armv7l;
    fi